packages:
  - "frontend"
  - "docs-site"
  - "marketing-site"
overrides:
  cookie: 0.7.2
onlyBuiltDependencies:
  - esbuild
  - sharp
  - vue-demi
allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
